"""The request the real agent builds (agent/tests/fixtures/contract/sync_all_kinds.json, generated by the agent's own
tests) is accepted by the cloud and handled as the contract says."""
import json
from datetime import timedelta
from pathlib import Path

import pytest

from app import agent_sync, sites
from app.catalogue import seed_catalogue
from app.models import ManagedJob
from app.seed import seed_tod
from tests.helpers import NOW, add_prices, evening_to_next_noon

FILE = Path(__file__).resolve().parents[2] / "agent" / "tests" / "fixtures" / "contract" / "sync_all_kinds.json"


@pytest.fixture()
def world(session):
    seed_tod(session)
    seed_catalogue(session)
    add_prices(session, NOW, evening_to_next_noon())
    site, _ = sites.create_site(session, "Acme", "Pune-1", gpus=64, mode="autonomous")
    return session, site


def status(session, ref):
    session.expire_all()
    j = session.query(ManagedJob).filter_by(ref=ref).one()
    return j.state, j.plan_status


def test_the_cloud_accepts_and_understands_the_agents_request(world):
    session, site = world
    body = agent_sync.SyncIn.model_validate(json.loads(FILE.read_text()))
    out = agent_sync.process_sync(session, site, body, NOW)

    assert out.release_all is True and out.decisions == []  # the request asked for release_all, so the kill switch is on
    assert status(session, "50_[1-3]") == ("PENDING", "skipped")
    assert status(session, "48214") == ("PENDING", "abandoned")  # user override, and the failed apply
    assert status(session, "48217")[1] == "released"
    assert status(session, "48213")[0] == "COMPLETED"
    job = session.query(ManagedJob).filter_by(ref="48213").one()
    assert job.actual_start is not None and job.actual_end is not None and job.gpus == 2
    assert session.query(ManagedJob).filter_by(ref="48211").one().applied_start is not None

    sites.set_release_all(session, site, False, NOW + timedelta(seconds=30))  # once an operator clears the switch...
    again = body.model_copy(update={"release_all": False, "applied": [], "released": []})
    out = agent_sync.process_sync(session, site, again, NOW + timedelta(seconds=60))
    assert out.release_all is False
    assert {d.ref for d in out.decisions} <= {"48211", "48215"}  # ...only still-pending, still-managed jobs are planned
